version: 0.2

env:
  secrets-manager:
    SMTP_SERVER: "myapp/smtp:server"
    SMTP_PORT: "myapp/smtp:port"
    SMTP_USERNAME: "myapp/smtp:username"
    SMTP_PASSWORD: "myapp/smtp:password"
    TO_EMAIL: "myapp/email:to"
    FROM_EMAIL: "myapp/email:from"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npx playwright install --with-deps
      - echo "Dependencies installed."

  build:
    commands:
      - echo "Running Playwright BDD Tests in headless mode..."
      - mkdir -p cucumber-report
      - npx cucumber-js "features/**/*.feature" \
        --require "tests/**/*.js" \
        --format json:cucumber-report/report.json || echo "Tests failed, continuing..."
      - echo "Ensuring reports directory exists..."
      - mkdir -p reports
      - echo "Generating HTML report..."
      - node generate-report.js || echo "Report generation failed or JSON invalid, continuing..."
      - ls -l reports || echo "Reports directory is empty"

  post_build:
    commands:
      - echo "Uploading report to S3..."
      - |
        REPORT_PATH="reports/cucumber-report.html"
        S3_BUCKET="my-playwright-reports"
        S3_KEY="${CODEBUILD_BUILD_ID}/cucumber-report.html"
        REPORT_PATH="reports/cucumber-report.html"  # Make sure this points to 
        if [ -f "$REPORT_PATH" ]; then
          echo "Found report file at: $REPORT_PATH"
          aws s3 cp "$REPORT_PATH" "s3://$S3_BUCKET/$S3_KEY" || echo "S3 upload failed, check IAM permissions"
          REPORT_URL="https://$S3_BUCKET.s3.amazonaws.com/$S3_KEY"
          echo "Report uploaded to $REPORT_URL"
        else
          echo "WARNING: Report file not found at $REPORT_PATH, skipping S3   upload."
          echo "Current directory contents:"
          ls -la
          REPORT_URL="Report not available"
        fi
      - echo "Sending email with SES..."
      - |
        aws ses send-email \
          --from "$FROM_EMAIL" \
          --destination "ToAddresses=$TO_EMAIL" \
          --message "Subject={Data=Playwright BDD Test Report - ${CODEBUILD_BUILD_ID}},Body={Text={Data=Report available at $REPORT_URL}}" || echo "SES email failed, check IAM permissions and verified emails"

artifacts:
  files:
    - cucumber-report/report.json
    - reports/cucumber-report.html
  discard-paths: yes
