version: 0.2

env:
  secrets-manager:
    SMTP_SERVER: "myapp/smtp:server"
    SMTP_PORT: "myapp/smtp:port"
    SMTP_USERNAME: "myapp/smtp:username"
    SMTP_PASSWORD: "myapp/smtp:password"
    EMAIL_RECEIVER: "myapp/smtp:to"

phases:
  build:
    commands:
      - echo "🔎 Debugging Secrets Manager values..."
      - echo "SMTP_SERVER=$SMTP_SERVER"
      - echo "SMTP_PORT=$SMTP_PORT"
      - echo "SMTP_USERNAME=$SMTP_USERNAME"
      - echo "SMTP_PASSWORD=**** (hidden for safety)"
      - echo "EMAIL_RECEIVER=$EMAIL_RECEIVER"
      - echo "CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID"
